### ISSUE TITLE
More documentation...

### ISSUE THREAD

**Issue by kalken** [juhaelee/hapi-massive#1]
Hello!

First of thanks for this awesomeness!

Sadly the documentation is lacking a bit and that makes me not knowing how to use it. I'm also very new to the concept of "promises" so this is what my question is about.

I'm trying to write a jsonapi which has to return the document up on creation. "this.db" is an instance created with this hapi-plugin. code is basically:

```
ResourceModel.prototype.addResource = function(newResource) {
    const newDoc = {
        fields: newResource.attributes.fields,
        categories: newResource.attributes.categories
    }

    let test = this.db.saveDocAsync("resources",newDoc).then(function(doc){
        //console.log(doc);
        return doc;
    });

   return ??? //need to return doc here.
};
```

I can't figure out how to return the value of "doc" in my "addResource"-function. A console log of doc inside the function gives me exactly what i want. But HOW can i wait for this function to complete and then return the value of doc as the return-value from the whole function?

**Comment by kalken** [comment]
Hmm i realized that i sort of didn't need a model so right now i've solved it in my controller by running the reply-statement inside the then-doc-function. Though i'm still interested in how i would wait for a call to finish and return its value outside of that function.

**Comment by juhaelee** [comment]
You want to return a promise here so that when you call `addResource` it can give you the value you need. Don't call `then` in the addResource prototype func. So your function should look like this:

``` javascript
ResourceModel.prototype.addResource = function(newResource) {
    const newDoc = {
        fields: newResource.attributes.fields,
        categories: newResource.attributes.categories
    }

    return this.db.saveDocAsync("resources",newDoc);
};
```

Then when you need the doc, you should call this function using this kind of syntax:

``` javascript
var newResource = // your new resource
ResourceModel.addResource(newResource).then(function(doc){
   console.log("woot got my doc here ", doc);
}).catch(function(err){
  console.err("oh no an error! ", err);
});

```

**Comment by kalken** [comment]
Thank you so much for this!

It's my suggestion that you add some small examples on how to do "nested" operations with promises and add that to readme. One small example would be to update only values that has has been requested to change (leaving everything else intact). I solve this by reading out the document from the database, update it where the data needs update and put it back again. This involves both reading and writing to the database in the same "run" of a request.

This library is an excellent addon to a hapi-backend and it would be nice if more people could get started quickly!

/K
